name: Unit Tests

on:
  push:
    branches:
      - main
      - release-2.[3-9]
  pull_request:
    branches:
      - main
      - release-2.[3-9]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set up Go
      uses: actions/setup-go@v3
      id: go
      with:
        go-version-file: go.mod

    - name: Unit Tests
      run: |
        make test
